version: "3.8"
services:
  db:
    image: "172.20.0.3:5000/vp_db"
    build:
      context: db/
      args:
        - DB_TOKEN_KEY
        - DB_ADMIN_PASSWORD
    volumes:
      - vp_couchdb_data:/opt/couchdb/data
    networks:
      user-bridge:
        ipv4_address: 172.20.0.21
    restart: unless-stopped
  app:
    image: "172.20.0.3:5000/vp_app"
    build:
      context: ..
      args:
        - DB_TOKEN_KEY
    environment:
      - BASE_URL=https://ba.azendorf.com
      - COUCHDB_URL=https://ba.azendorf.com:5984
      - SSO_URL=https://ba.azendorf.com/api/user/testSso
    networks:
      user-bridge:
        ipv4_address: 172.20.0.20
    depends_on:
      - db
    restart: unless-stopped

volumes:
  vp_couchdb_data:

networks:
  user-bridge:
    external: true
